trigger:
  - master
  
pool:
  vmImage: 'windows-latest' 

variables:
  buildConfiguration: 'Release'
  projectName: '**/DoctorManagement.API.csproj'
  drop: '$(Build.ArtifactStagingDirectory)/drop'

stages: 
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Job'
        steps:
         - task: Bash@3
           inputs:
             targetType: 'inline'
             packageType: 'sdk'
             version: '10.0.x'
             script: |
              dotnet workload restore
              dotnet publish --configuration $(buildConfiguration) --output $(drop)
                      