apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.appName}}-service"
  labels:
    app: {{.Values.appName}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 8080 # Port on the Pod where the application is listening
  type: ClusterIP # Or NodePort, LoadBalancer, ExternalName