<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="DartSassBuilder" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoctorManagement.Api.Consumer\DoctorManagement.Api.Consumer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>



</Project>
