<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.JSInterop" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DataSourceTypeCodes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataSourceTypeCodes.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="DataSourceTypeCodes.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DataSourceTypeCodes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
