<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoctorManagement.DataAccessLayer\DoctorManagement.DataAccessLayer.csproj" />
    <ProjectReference Include="..\DoctorManagement.Integrations\DoctorManagement.Integrations.csproj" />
  </ItemGroup>

</Project>
